## Docker Compose cheat sheet

## Ports
##   host:container
##   http  > '80${port}'
##   https > '443${port}'
##   search regex: (80[0-9]+|443[0-9]+):
##
## Reserved Ports
##   - 8090 Matrix identity server
##
## Volumes
##   /Host/Location:/Container/Location

include:
  - management.yaml
#  - web.yaml
#  - storage.yaml
#  - network.yaml
#  - media.yaml