## Docker Compose cheat sheet

## Ports
##   host:container
##   http  > '80${port}'
##   https > '443${port}'
##   search regex: (80[0-9]*|443[0-9]*):
##
## Reserved Ports
##   - 8090 Matrix identity server
##
## Volumes
##   - type: bind
##     source: /Host/Location
##     target: /Container/Location

services:
  ## Docker Container Management
  ## https://wiki.serversatho.me/
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8085:8000 # Portainer http
      - 44385:9443 # Portainer https
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind 
        source: ${STORAGE}/configs/portainer
        target: /data

  ## Pi-hole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80/tcp" # Pi-hole http
      - "44382:443/tcp" # Pi-hole https
    environment:
      TZ: '${TIMEZONE}'
      FTLCONF_webserver_api_password: 'changeme'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - type: bind 
        source: ${STORAGE}/configs/pihole
        target: /etc/pihole
    restart: unless-stopped